### PR TITLE
Integrate rs-ucan

### PR DESCRIPTION
**Pull request by icidasset**
## Capabilities to support

```js
{
  // Allow anything
  "did:<method>:<details>": { "*": [{}] },

  // Delegate all capabilities
  "ucan:*": { "ucan/*": [{}] },
}
```

### CODE REVIEW

**Comment by expede** [comment]
I'm not certain that it makes sense to have capabilities for things that anyone can do 🤔 Do they need permission to create a developer account or an account relative to an application? Anyone can sign up for these, right?

I think that some data may be in the wrong fields, but the notes may be a sketch only. I'd suggest changing...

```js
// Today:
{
  "?": {
    "crud/create": [
      { "type": "APPLICATION", "did": "did:dns:app.fission.app" },
      { "type": "DEVELOPER" }
    ]
  }
}
```

...to something like this...


```js
// Create an app at myapp.fission.app
{
  "https://myapp.fission.app/accounts": {
    "crud/create": []
  }
}

// Create accounts relative to the app, though I'm pretty sure that anyone can do that, right?

{
  "volume://myapp.fission.app": {
    "crud/create": [
      { "username": "*" }
    ]
  }
}
```

There's a few reasons

1. Redundancy: in the original, we can tell that it's an app being created in the resource, action, and extended (NB) fields
2. The resource should target the thing being interacted with rather than pushing it into the ended caveats.
3. You can always create an account; I'm pretty sure that there's nothing to delegate to the user

Let's chat about this stuff on a quick call on Monday, though :)

**Comment by icidasset** [comment]
> I'm not certain that it makes sense to have capabilities for things that anyone can do

@expede I just threw that in as a capability example to start off with, not an actual capability. These indeed don't need capabilities, definitely not developer accounts. App accounts perhaps if we wanted to push more logic to the client by adding a UCAN to the app's static files and using that as proof to create an app account. But we're not doing that I assume.

> The resource should target the thing being interacted with

👍 Changes look good!

**Comment by expede** [comment]
@icidasset 

> What if the client issues a UCAN to the Fission server that says "you can create an account with this did:key" (account creation capability) and then the server gives you back a UCAN that says "you've now got a Fission account and this unlocks all these capabilities" (fission account capabilities) ?

Ah, it could be a framing thing. What you wrote above sounds different to me from a "you can create an account". It's more like "here's a proof that you can administer this existing account", which I read as the other way around from the initial framing. It's not permission to create an account, it's a handle to the account that you already created (i.e. you were promoted from "anonymous user" to "account manager for this username at Fission Codes"). You only need auth in cases of preventing the general public from doing things; it's talks about what you can do, not who you are or what your role is.

Does that make sense?

**Comment by icidasset** [comment]
> What you wrote above sounds different to me from a "you can create an account". It's more like "here's a proof that you can administer this existing account"
>  It's not permission to create an account, it's a handle to the account that you already created

Yeah depends on what you consider the key pair on the client to be I guess. I don't consider it to be an account, I see it as a key pair which becomes associated with an account the moment you send it to the Fission server.

> it's talks about what you can do, not who you are or what your role is.

Totally makes sense yeah. To be clear, I don't want the UCAN to say which role it has, I want it to have app or developer account capabilities.

Also just to clarify, I'm just exploring ideas/possibilities here.

**Comment by expede** [comment]
> Yeah depends on what you consider the key pair on the client to be I guess. I don't consider it to be an account, I see it as a key pair which becomes associated with an account the moment you send it to the Fission server.

I agree with that, but still don't think that you would get a UCAN that lets you create an account, because anyone is allowed to do so 🤔

**Comment by expede** [comment]
> Also just to clarify, I'm just exploring ideas/possibilities here.

Yeah absolutely! Sorry if it came off strongly or something; I'm also working through this stuff with you, but possibly bringing some additional background from stuff I've seen other orgs use UCAN and other capability systems since we developed the original server way back when. That doesn't mean that the approach I'm suggesting is more correct automatically — I'm just noting where things sound off to me as we figure out what the APIs should look like.

**Comment by icidasset** [comment]
> don't think that you would get a UCAN that lets you create an account, because anyone is allowed to do so

Yeah 🤔 Just out of curiosity... What if you view the situation from the client's key pair's perspective? eg. the client allows the fission server to use the key pair to associate it with an account. Although I guess that doesn't make much sense, because the fission server can't actually do anything with the key pair itself, it only serves as an identifier, the DID.

**Pull request closed without merging**
